# This is a basic workflow to help you get started with Actions

name: Install CI

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install jdk
        uses: actions/setup-jdk@v1
        with:
          jdk-version : '11.x'
